name: Build Arduino Examples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli core update-index --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          arduino-cli core install rp2040:rp2040 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "Adafruit NeoPixel"

      - name: Compile examples
        run: |
          for sketch in $(find xDuinoRails_LED-Drivers/examples -name "*.ino"); do
            echo "Compiling $sketch"
            arduino-cli compile --fqbn rp2040:rp2040:seeed_xiao_rp2040 $sketch
          done
